import { Link, useLocation } from 'wouter';
import { motion } from 'framer-motion';
import { ArrowLeft, Download, Calendar, User, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import RadialGauge from '@/components/RadialGauge';
import MotivationalCard from '@/components/MotivationalCard';
import { jsPDF } from 'jspdf';

export default function SessionDetails() {
  const [location] = useLocation();
  const isTherapist = location.includes('therapist');

  //todo: remove mock functionality
  const sessionData = {
    sessionId: 'S003',
    date: 'Oct 15, 2025',
    classification: 'Articulation Disorder',
    confidence: 86,
    patientName: 'Abdulla A.',
    patientAge: 7,
    patientEmail: 'Abdulla.A@example.com',
    therapist: 'Dr. Sarah Thompson',
    sentencesUsed: [
      'Kenny drank a tiny tin of coke',
      'Sean the sheep was on the ship',
      'Funny Sean was washing a dirty dish',
      "Cheeky Charlie's watching a football match",
      'My granny Maggie got a golden gown',
    ],
    aiNotes: 'The patient demonstrated good effort during the session. Some mispronunciation patterns were detected in alveolar consonants, particularly /r/ and /s/ phonemes. Continued practice with tongue placement exercises is recommended.',
    recommendations: [
      'Continue with regular practice sessions focusing on articulation',
      'Practice tongue placement exercises for /r/ and /s/ sounds',
      'Recommended follow-up: 2 sessions per week',
    ],
  };

  const motivationalMessages = [
    "Great job on completing this session! Your pronunciation is getting better with each practice.",
    "Keep up the excellent work! Remember, practice makes perfect, and you're doing wonderfully.",
  ];

  const handleDownloadReport = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(168, 200, 194);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('Nabra', 20, 20);
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text('Speech Therapy Session Report', 20, 30);
    
    // Patient Information
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Patient Information', 20, 55);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${sessionData.patientName}`, 20, 65);
    doc.text(`Age: ${sessionData.patientAge} years`, 20, 72);
    doc.text(`Email: ${sessionData.patientEmail}`, 20, 79);
    doc.text(`Assigned Therapist: ${sessionData.therapist}`, 20, 86);
    
    // Session Details
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Session Details', 20, 100);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Session ID: ${sessionData.sessionId}`, 20, 110);
    doc.text(`Date: ${sessionData.date}`, 20, 117);
    
    // Analysis Results
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Analysis Results', 20, 135);
    
    doc.setFillColor(240, 249, 255);
    doc.rect(20, 142, 170, 35, 'F');
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Classification:', 25, 152);
    doc.setFont('helvetica', 'normal');
    doc.text(sessionData.classification, 25, 160);
    
    doc.setFont('helvetica', 'bold');
    doc.text('Confidence Score:', 25, 170);
    doc.setFontSize(18);
    doc.setTextColor(76, 175, 80);
    doc.text(`${sessionData.confidence}%`, 25, 178);
    
    // AI Observations
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('AI Observations', 20, 195);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const observations = doc.splitTextToSize(sessionData.aiNotes, 170);
    doc.text(observations, 20, 205);
    
    // Recommendations
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Recommendations', 20, 230);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    sessionData.recommendations.forEach((rec, index) => {
      doc.text(`• ${rec}`, 20, 240 + (index * 7));
    });
    
    // Footer
    doc.setFillColor(240, 240, 240);
    doc.rect(0, 275, 210, 22, 'F');
    
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by Nabra Platform', 20, 285);
    doc.text(`Report generated on: ${new Date().toLocaleDateString()}`, 20, 291);
    
    // Save the PDF
    doc.save(`Nabra_Report_${sessionData.sessionId}_${sessionData.patientName.replace(/\s+/g, '_')}.pdf`);
  };

  const backUrl = isTherapist ? '/dashboard/therapist' : '/dashboard/patient';

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border bg-card/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href={backUrl}>
            <Button variant="ghost" size="sm" data-testid="button-back">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Dashboard
            </Button>
          </Link>
          <Button onClick={handleDownloadReport} data-testid="button-download-report">
            <Download className="w-4 h-4 mr-2" />
            Download Report
          </Button>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-8"
        >
          <div>
            <h1 className="text-4xl font-bold text-foreground mb-2">Session Details</h1>
            <p className="text-lg text-muted-foreground">
              Complete analysis and results for {sessionData.sessionId}
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            <Card>
              <CardContent className="p-6 flex items-center gap-4">
                <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                  <Calendar className="w-6 h-6 text-primary" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Session Date</p>
                  <p className="text-lg font-semibold text-foreground">{sessionData.date}</p>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6 flex items-center gap-4">
                <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                  <User className="w-6 h-6 text-primary" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Patient</p>
                  <p className="text-lg font-semibold text-foreground">{sessionData.patientName}</p>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6 flex items-center gap-4">
                <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                  <FileText className="w-6 h-6 text-primary" />
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Session ID</p>
                  <p className="text-lg font-semibold text-foreground">{sessionData.sessionId}</p>
                </div>
              </CardContent>
            </Card>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            <Card>
              <CardHeader>
                <CardTitle>Analysis Results</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="flex justify-center">
                  <RadialGauge value={sessionData.confidence} label="Confidence Score" size={200} />
                </div>
                <div className="text-center space-y-2">
                  <p className="text-sm text-muted-foreground">Classification</p>
                  <Badge className="text-base px-4 py-1 bg-chart-1/10 text-chart-1">
                    {sessionData.classification}
                  </Badge>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Patient Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Name</p>
                    <p className="text-base font-medium text-foreground">{sessionData.patientName}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Age</p>
                    <p className="text-base font-medium text-foreground">{sessionData.patientAge} years</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Email</p>
                    <p className="text-base font-medium text-foreground">{sessionData.patientEmail}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Assigned Therapist</p>
                    <p className="text-base font-medium text-foreground">{sessionData.therapist}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>Sentences Practiced</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                {sessionData.sentencesUsed.map((sentence, index) => (
                  <div key={index} className="flex items-start gap-3 p-3 bg-muted/30 rounded-lg">
                    <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center text-sm font-semibold text-primary">
                      {index + 1}
                    </span>
                    <p className="text-foreground">{sentence}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>AI Observations</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground leading-relaxed">{sessionData.aiNotes}</p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Recommendations</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                {sessionData.recommendations.map((rec, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <span className="w-2 h-2 rounded-full bg-primary mt-2 flex-shrink-0" />
                    <p className="text-foreground">{rec}</p>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          {!isTherapist && (
            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Encouraging Words</h2>
              {motivationalMessages.map((message, index) => (
                <MotivationalCard
                  key={index}
                  message={message}
                  icon={index === 0 ? 'trophy' : 'star'}
                />
              ))}
            </div>
          )}
        </motion.div>
      </main>
    </div>
  );
}
